name: CI
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, World!
  
  deploy-dev:
    runs-on: ubuntu-latest
    environment:
      name: Dev
      url: 'qa-coders-ronbugado.com.br/dev'
    needs: build
    steps:
      - name: Run a one-line script
        run: echo Deploy dev
        
  deploy-hmg:
    runs-on: ubuntu-latest
    environment:
      name: Homologação
      url: 'http://191.252.210.196/ronbugado'
    needs: deploy-dev
    steps:
      - uses: actions/checkout@master
      - uses: matt-ball/newman-action@master
        with:
          collection: RestFull_collection
          environment: RestFull_environment
      - name: Run a one-line script
        run: echo Deploy HMG
      
  
  deploy-prd:
    runs-on: ubuntu-latest
    environment:
      name: Produção
      url: 'qa-coders-ronbugado.com.br/prd'
    needs: deploy-hmg
    steps:
      - name: Run a one-line script
        run: echo Deploy PRD
        
